# Generated by Django 5.2.6 on 2025-10-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название контакта'),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
