# Generated by Django 5.2.6 on 2025-10-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_contact_alter_contactdata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип контакта (например, Email, Телефон)'),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение (адрес, номер, email и т.п.)'),
        ),
    ]
