# Generated by Django 5.2.6 on 2025-10-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_contactdata_name_alter_contactdata_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactData',
        ),
    ]
